sonar.projectKey=SUBSTITUIR_PELA_PROJECT_KEY
sonar.organization=SUBSTITUIR_PELA_ORGANIZATION
sonar.sources=src
sonar.exclusions=**/*.test.ts
sonar.tests=src
sonar.test.inclusions=**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
